name: x2ct_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.9.23=hc30ae73_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - contourpy==1.3.0
      - cycler==0.12.1
      - dominate==2.9.1
      - easydict==1.13
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - h5py==3.14.0
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==11.3.0
      - protobuf==6.33.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - scikit-image==0.24.0
      - scipy==1.13.1
      - simpleitk==2.5.2
      - six==1.17.0
      - sympy==1.14.0
      - tensorboardx==2.6.4
      - tifffile==2024.8.30
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - triton==3.4.0
      - typing-extensions==4.15.0
      - zipp==3.23.0
prefix: /home/matheus/miniforge3/envs/x2ct_env
